### ISSUE TITLE
[UpgradeService] Error while fetching the version info 

### ISSUE THREAD

**Issue by theseusyang** [hisorange/artgen#5]
[main][03:42:40.922][info][LogicHttpGateway] WebHook [ced473f0][trigger.http.26] registered to [POST][/api/identity/signup] 
[main][03:42:40.924][info][LogicHttpGateway] WebHook [51c0abf2][trigger.http.1] registered to [POST][/api/authentication/jwt/sign-in] 
[main][03:42:41.171][info][HttpService] Upstream [1] ready, prepared in [577] ms 
[main][03:42:41.173][info][Kernel] Startup procedure is finished, application is ready! 
[main][03:42:45.686][error][UpgradeService] Error while fetching the version info

**Comment by hisorange** [comment]
Will be removed in the next release, the upgrade system supposed to notify the developers about a new version, but it will be moved to the UI, there is no need to run this on the backend since it's just an HTTP request.

The system is prepared to catch this warning and works without an issue, also the boot does not wait for this to execute.
